# Database configuration for Temporal using PostgreSQL as the persistence and visibility store.
server:
  image:
    repository: temporalio/server
    tag: 1.30.3
  # Replicas and resources for the Temporal server
  replicaCount: 1

  archival:
    history:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          region: "us-east-1"
          endpoint: "http://localstack.localstack.svc.cluster.local:4566"
          s3ForcePathStyle: true
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        s3store:
          region: "us-east-1"
          endpoint: "http://localstack.localstack.svc.cluster.local:4566"
          s3ForcePathStyle: true

  namespaceDefaults:
    archival:
      history:
        state: "enabled"
        URI: "s3://aws-archival"
      visibility:
        state: "enabled"
        URI: "s3://aws-archival-visibility"

  config:
    metrics:
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"
    namespaces:
      create: true
      namespace:
        - name: approval-namespace
          retention: 30d
        - name: approval-namespace2
          retention: 1h
        - name: default
          retention: 1h
    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: 512
      datastores:
        default:
          sql:
            createDatabase: false
            manageSchema: true
            pluginName: postgres12_pgx
            databaseName: tmprldcd
            connectAddr: "192.168.49.1:54320"
            connectProtocol: "tcp"
            user: "cnxtmpld"
            connectAttributes:
              search_path: "tmpld"
            existingSecret: aws-secret-rds-temporal
            secretKey: password
            maxConns: 5
            maxIdleConns: 2
            maxConnLifetime: "1h"
        visibility:
          sql:
            createDatabase: false
            manageSchema: true
            pluginName: postgres12_pgx
            databaseName: tmplvdcd
            connectAddr: "192.168.49.1:54320"
            connectProtocol: "tcp"
            user: "cnxtmpld"
            connectAttributes:
              search_path: "tmplv"
            existingSecret: aws-secret-rds-temporal
            secretKey: password
            maxConns: 5
            maxIdleConns: 2
            maxConnLifetime: "1h"
  additionalEnvSecretName: "aws-secret-rds-temporal"
  additionalEnv:
    - name: AWS_ACCESS_KEY_ID
      value: "test"
    - name: AWS_SECRET_ACCESS_KEY
      value: "test"
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_ENDPOINT_URL
      value: "http://localstack.localstack.svc.cluster.local:4566"
    - name: AWS_ENDPOINT_URL_S3
      value: "http://localstack.localstack.svc.cluster.local:4566"
    - name: AWS_S3_FORCE_PATH_STYLE
      value: "true"
    - name: SQL_HOST
      valueFrom:
        secretKeyRef:
          name: aws-secret-rds-temporal
          key: host
    - name: SQL_PORT
      valueFrom:
        secretKeyRef:
          name: aws-secret-rds-temporal
          key: port
    - name: SQL_USER
      valueFrom:
        secretKeyRef:
          name: aws-secret-rds-temporal
          key: username
    - name: SQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: aws-secret-rds-temporal
          key: dbname
  frontend:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi
    additionalEnv:
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_REGION
        value: "us-east-1"
      - name: AWS_ENDPOINT_URL
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_ENDPOINT_URL_S3
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_S3_FORCE_PATH_STYLE
        value: "true"

  history:
    # Replicas and resources for the history service
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 1G
    additionalEnv:
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_REGION
        value: "us-east-1"
      - name: AWS_ENDPOINT_URL
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_ENDPOINT_URL_S3
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_S3_FORCE_PATH_STYLE
        value: "true"
    
  matching:
    # Replicas and resources for the matching service
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi
    additionalEnv:
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_REGION
        value: "us-east-1"
      - name: AWS_ENDPOINT_URL
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_ENDPOINT_URL_S3
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_S3_FORCE_PATH_STYLE
        value: "true"
    

  worker:
    # Replicas and resources for the worker service
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 2
        memory: 2Gi
    additionalEnv:
      - name: AWS_ACCESS_KEY_ID
        value: "test"
      - name: AWS_SECRET_ACCESS_KEY
        value: "test"
      - name: AWS_REGION
        value: "us-east-1"
      - name: AWS_ENDPOINT_URL
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_ENDPOINT_URL_S3
        value: "http://localstack.localstack.svc.cluster.local:4566"
      - name: AWS_S3_FORCE_PATH_STYLE
        value: "true"

## Version temporal
admintools:
  image:
    repository: temporalio/admin-tools
    tag: 1.30.3
  additionalEnv:
    - name: AWS_ACCESS_KEY_ID
      value: "test"
    - name: AWS_SECRET_ACCESS_KEY
      value: "test"
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_ENDPOINT_URL
      value: "http://localstack.localstack.svc.cluster.local:4566"

shims:
  dockerize: false
  elasticsearchTool: false

web:
  enabled: true
  image:
    repository: temporalio/ui
    tag: 2.49.1
  replicaCount: 1
  additionalEnv:
    - name: AWS_ACCESS_KEY_ID
      value: "test"
    - name: AWS_SECRET_ACCESS_KEY
      value: "test"
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_ENDPOINT_URL
      value: "http://localstack.localstack.svc.cluster.local:4566"

# Congiguracion para darle control a ArgoCD sobre el schema de la base de datos, para que lo ejecute antes del deploy del server
schema:
  useHelmHooks: true
  ttlSecondsAfterFinished: 300
#   jobAnnotations:
#     argocd.argoproj.io/hook: PreSync
#     argocd.argoproj.io/sync-wave: "0"
#     argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
